Disable GCC warning address-of-packed-member
Add -Wno-address-of-packed-member to Makefile to avoid
overzealous warnings (and thus errors) from GCC 9:
kernel/bridge.c:251:26: error: taking address of packed member of 'struct pi_task_implem' may result in an unaligned pointer value [-Werror=address-of-packed-member]
  251 |   rt_bridge_req_t *req = &event->implem.bridge_req;
      |                          ^~~~~~~~~~~~~~~~~~~~~~~~~